swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Sample API
  description: This is a sample API documentation using Swagger.
  contact:
    name: John Doe
    email: john.doe@example.com
    url: https://example.com
host: api.example.com
basePath: /v1
schemes:
  - https
  - http
paths:
  /api/v1/users:
    get:
      summary: Get a list of users
      description: Retrieve a list of users from the database.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
definitions:
  User:
    type: object
    properties:
      name:
        type: string
        minLength: 5

      surname:
        type: string
        minLength: 5

      email:
        type: string
        format: email
      photo:
        type: string
        default: "photo.jpg"
      password:
        type: string
        minLength: 8
      passwordConfirm:
        type: string
      role:
        type: string
        enum: ["admin", "user"]
        default: "user"
      jins:
        type: string
        enum: ["erkak", "ayol"]
      active:
        type: boolean
        default: true
  Product:
    type: object
    properties:
      name:
        type: string
        minLength: 5

      price:
        type: number
        minimum: 0
      description:
        type: string
        minLength: 5

      photo:
        type: string
        default: "photo.jpg"
      category:
        type: string
        enum: ["food", "drink"]
        default: "food"
      active:
        type: boolean
        default: true  