swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Sample API
  description: This is a sample API documentation using Swagger.
  contact:
    name: John Doe
    email: john.doe@example.com
    url: https://example.com
host: api.example.com
basePath: /v1
schemes:
  - https
  - http
paths:
  /users:
    get:
      summary: Get a list of users
      description: Retrieve a list of users from the database.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      email:
        type: string
      address:
        type: object
        properties:
          street:
            type: string
          city:
            type: string
          state:
            type: string
          zip:
            type: string
