openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8080
    description: Bu url localhostdagi server uchun
  - url: http://18.181.217.30:8000
    description: Bu url esa staging server uchun

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: cookie
      name: cart
security:
  - bearerAuth: []

paths:
  /api/v1/users:
    get:
      tags:
        - Users
      security:
        - bearerAuth: []
      summary: Hamma foydalanuvchilar ro'yhati.
      description: Hamma foydalanuvchilar ro'yhatini ko'rish faqat admin uchun.
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/users/{id}:
    get:
      tags:
        - Users
      security:
        - bearerAuth: []
      summary: Foydalanuvchi haqida ma'lumot.
      description: Foydalanuvchi haqida ma'lumotni ko'rish faqat admin uchun.
      parameters:
        - name: id
          in: path
          description: Foydalanuvchi ID si.
          required: true
          schema:
            type: string
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/users/:
    post:
      tags:
        - Users
      security:
        - bearerAuth: []
      summary: Foydalanuvchi yaratish.
      description: Foydalanuvchi yaratish faqat admin uchun.
      requestBody:
        description: Foydalanuvchi haqida ma'lumot.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                jins:
                  type: string
                  enum:
                    - erkak
                    - ayol
      responses:
        "200": # status code
          description: Foydalanuvchi qaytadi.
          content:
            application/json:
              schema:
                type: object
  /api/v1/users/{id}/:
    patch:
      tags:
        - Users
      security:
        - bearerAuth: []
      summary: Foydalanuvchi haqida ma'lumot.
      description: Foydalanuvchi haqida ma'lumotni o'zgartirish faqat admin uchun.
      parameters:
        - name: id
          in: path
          description: Foydalanuvchi ID si.
          required: true
          schema:
            type: string
      requestBody:
        description: Foydalanuvchi haqida ma'lumot.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                password:
                  type: string

      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/users/{idcha}/:
    delete:
      tags:
        - Users
      security:
        - bearerAuth: []
      summary: Foydalanuvchi haqida ma'lumot.
      description: Foydalanuvchi haqida ma'lumotni o'zgartirish faqat admin uchun.
      parameters:
        - name: idcha
          in: path
          description: Foydalanuvchi ID si.
          required: true
          schema:
            type: string
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object

  /api/v1/products:
    get:
      tags:
        - Products
      summary: Hamma mahsulotlar ro'yhati.
      description: Hamma mahsulotlar ro'yhatini ko'rish faqat admin uchun.
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/products/{id}:
    get:
      tags:
        - Products
      summary: Mahsulot haqida ma'lumot.
      description: Mahsulot haqida ma'lumotni ko'rish faqat admin uchun.
      parameters:
        - name: id
          in: path
          description: Mahsulot ID si.
          required: true
          schema:
            type: string
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/products/{id}/:
    patch:
      tags:
        - Products
      security:
        - bearerAuth: []
      summary: Mahsulot haqida ma'lumot.
      description: Mahsulot haqida ma'lumotni o'zgartirish faqat admin uchun.
      parameters:
        - name: id
          in: path
          description: Mahsulot ID si.
          required: true
          schema:
            type: string
      requestBody:
        description: Mahsulot haqida ma'lumot.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: string
                image:
                  type: string
                category:
                  type: string
                quantity:
                  type: string
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/products/:
    post:
      tags:
        - Products
      security:
        - bearerAuth: []
      summary: Mahsulot yaratish.
      description: Mahsulot yaratish faqat admin uchun.
      requestBody:
        description: Mahsulot haqida ma'lumot.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: string
                category:
                  type: string
                expire:
                  type: string
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                category:
                  type: string
                salePrice:
                  type: number
                expire:
                  type: string
                image:
                  type: string
                  format: binary
      responses:
        "200": # status code
          description: Mahsulot qaytadi.
          content:
            application/json:
              schema:
                type: object
  /api/v1/products/{idcha}/:
    delete:
      tags:
        - Products
      security:
        - bearerAuth: []
      summary: Mahsulot haqida ma'lumot.
      description: Mahsulot haqida ma'lumotni o'chirish faqat admin uchun.
      parameters:
        - name: idcha
          in: path
          description: Mahsulot ID si.
          required: true
          schema:
            type: string
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/auth/signup:
    post:
      tags:
        - Auth
      summary: Ro'yxatdan o'tish.
      description: Ro'yxatdan o'tish uchun ma'lumotlarni yuborish.
      requestBody:
        description: Ro'yxatdan o'tish uchun ma'lumotlar.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                password:
                  type: string
                passwordConfirm:
                  type: string
                jins:
                  type: string
                  enum:
                    - erkak
                    - ayol
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                password:
                  type: string
                passwordConfirm:
                  type: string
                jins:
                  type: string
                  enum:
                    - erkak
                    - ayol
                image:
                  type: string
                  format: binary
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Kirish.
      description: Kirish uchun ma'lumotlarni yuborish.
      requestBody:
        description: Kirish uchun ma'lumotlar.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object

  /api/v1/auth/updatepassword:
    post:
      tags:
        - Auth
      security:
        - bearerAuth: []
      summary: Parolni o'zgartirish.
      description: Parolni o'zgartirish uchun ma'lumotlarni yuborish.
      requestBody:
        description: Parolni o'zgartirish uchun ma'lumotlar.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                password:
                  type: string
                passwordConfirm:
                  type: string
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object

  /api/v1/auth/logout:
    get:
      tags:
        - Auth
      security:
        - bearerAuth: []
      summary: Chiqish.
      description: Chiqish uchun ma'lumotlarni yuborish.
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/auth/me:
    get:
      tags:
        - Auth
      security:
        - bearerAuth: []
      summary: Ma'lumot.
      description: Ma'lumot olish uchun ma'lumotlarni yuborish.
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/auth/updateme:
    post:
      tags:
        - Auth
      security:
        - bearerAuth: []
      summary: Ma'lumot.
      description: Ma'lumot olish uchun ma'lumotlarni yuborish.
      requestBody:
        description: Ma'lumot olish uchun ma'lumotlar.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                jins:
                  type: string
                  enum:
                    - erkak
                    - ayol
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                jins:
                  type: string
                  enum:
                    - erkak
                    - ayol
                image:
                  type: string
                  format: binary
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object

  /api/v1/cart/getcart:
    get:
      tags:
        - Cart
      security:
        - bearerAuth: []
      summary: Savat.
      description: Savatni olish uchun ma'lumotlarni yuborish.
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/cart/addtocart:
    post:
      tags:
        - Cart
      security:
        - bearerAuth: []
      summary: Savatga qo'shish.
      description: Savatga qo'shish uchun ma'lumotlarni yuborish.
      requestBody:
        description: Savatga qo'shish uchun ma'lumotlar.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                      count:
                        type: number
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object

  /api/v1/cart/paymentcart:
    get:
      tags:
        - Cart
      security:
        - bearerAuth: []
      summary: Savatni to'lash.
      description: Savatni to'lash uchun ma'lumotlarni yuborish.
      responses:
        "200": # status code
          description: A JSON array of usernames
          content:
            application/json:
              schema:
                type: object
  /api/v1/cart/deletecart:
    get:
      tags:
        - Cart
      security:
        - bearerAuth: []
      summary: Savatni to'lash.
      description: Savatni to'lash uchun ma'lumotlarni yuborish.
      responses:
        "200": # status code
          description: A JSON array of usernames
          headers:
            set-cookie:
              schema:
                type: string
                description: A cookie
          content:
            application/json:
              schema:
                type: object
